# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtransferfeepayment',
            name='transferred_size',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
