# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_landtransferfeepayment_transferred_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtransferfeepayment',
            name='land',
        ),
        migrations.RemoveField(
            model_name='landtransferfeepayment',
            name='user',
        ),
        migrations.AddField(
            model_name='landtransferfeepayment',
            name='land_title_deed',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
