# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
    ]
