# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_deed_no', models.CharField(max_length=32)),
                ('registry_map_sheet_no', models.CharField(max_length=32)),
                ('approximate_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Land Owner')),
            ],
        ),
        migrations.CreateModel(
            name='LandTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title_deed_no', models.CharField(max_length=32)),
                ('transfer_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='New Owner')),
                ('old_title_deed_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='land.Land')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LandOwner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='LandUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.PositiveIntegerField(verbose_name='National ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('district', models.CharField(max_length=128)),
                ('ward', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
