# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLandOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_title_deed_no', models.CharField(max_length=32)),
                ('new_title_deed_no', models.CharField(max_length=32)),
                ('transfer_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='New Owner')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LandOwner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_deed_no', models.CharField(max_length=32, unique=True)),
                ('registry_map_sheet_no', models.CharField(max_length=32, unique=True)),
                ('approximate_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('is_onsale', models.BooleanField(default=True)),
                ('bought', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=32)),
                ('buyer', models.CharField(max_length=32)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncleared_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_made', models.BooleanField(default=False)),
                ('date_deposited', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.Land')),
            ],
        ),
        migrations.CreateModel(
            name='LandTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('id_no', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('sub_location', models.CharField(max_length=128)),
                ('transfer_from', models.CharField(max_length=128)),
                ('transfer_size', models.FloatField()),
                ('title_deed', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.Land')),
            ],
        ),
        migrations.CreateModel(
            name='LandTransferHistoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_from', models.CharField(max_length=128)),
                ('transfer_to', models.CharField(max_length=128)),
                ('initial_title_deed', models.CharField(max_length=128)),
                ('initial_map_sheet', models.CharField(max_length=128)),
                ('new_map_sheet', models.CharField(max_length=128)),
                ('new_title_deed', models.CharField(max_length=128)),
                ('date_transferred', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.PositiveIntegerField(verbose_name='National ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('district', models.CharField(max_length=128)),
                ('ward', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=13)),
                ('sent_to', models.CharField(default='', max_length=13)),
                ('text', models.TextField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('land_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='land.Land')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.AddField(
            model_name='land',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.LandUserProfile'),
        ),
        migrations.AddField(
            model_name='land',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Land Owner'),
        ),
    ]
