# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtransfer',
            name='map_sheet',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
