# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_onsale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='registry_map_sheet_no',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='title_deed_no',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Land Owner'),
        ),
    ]
