# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
