# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_auto_20161009_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
