# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_land_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandTransferHistoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_from', models.CharField(max_length=128)),
                ('transfer_to', models.CharField(max_length=128)),
                ('initial_map_sheet', models.CharField(max_length=128)),
                ('new_map_sheet', models.CharField(max_length=128)),
                ('initial_title_deed', models.CharField(max_length=128)),
                ('new_title_deed', models.CharField(max_length=128)),
                ('date_transferred', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
