# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_landtransferhistorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
