# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_notification_responded'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=32)),
                ('buyer', models.CharField(max_length=32)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncleared_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_deposited', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.Land')),
            ],
        ),
    ]
