# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_delete_landtransfercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtransfer',
            name='land',
        ),
    ]
