# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_remove_landtransfer_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='remaining_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='land',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
