# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_landsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsales',
            name='transfer_made',
            field=models.BooleanField(default=False),
        ),
    ]
