# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_auto_20161110_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='transferred',
            new_name='transferred_completely',
        ),
    ]
