# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_auto_20161110_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsales',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landtransfer',
            name='old_title_deed',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landtransfer',
            name='title_deed',
            field=models.CharField(max_length=128),
        ),
    ]
